/** A big searchable named-color library for picking filament colors. Mix of common filament colors,
 *  Bambu/brand names, and the full CSS/X11 named set. Search by name in the AMS slot editor. */
export type NamedColor = { name: string; hex: string };

export const COLOR_LIBRARY: NamedColor[] = [
	// Filament-common + the ones people actually ask for
	{ name: 'Clear', hex: '#EAF2F8' },
	{ name: 'Natural', hex: '#EDE6D6' },
	{ name: 'Transparent', hex: '#E8F0F2' },
	{ name: 'Black', hex: '#161616' },
	{ name: 'Matte Black', hex: '#1C1C1C' },
	{ name: 'Jet Black', hex: '#0A0A0A' },
	{ name: 'White', hex: '#F5F5F5' },
	{ name: 'Matte White', hex: '#FAFAFA' },
	{ name: 'Ivory White', hex: '#FFFFF0' },
	{ name: 'Bone White', hex: '#E3DAC9' },
	{ name: 'Gray', hex: '#8E8E8E' },
	{ name: 'Grey', hex: '#8E8E8E' },
	{ name: 'Light Gray', hex: '#C7C7C7' },
	{ name: 'Dark Gray', hex: '#4A4A4A' },
	{ name: 'Ash Gray', hex: '#B2BEB5' },
	{ name: 'Silver', hex: '#C0C0C0' },
	{ name: 'Silver Metallic', hex: '#A9A9B0' },
	{ name: 'Gunmetal', hex: '#2A3439' },
	{ name: 'Nardo Gray', hex: '#6E7274' },

	{ name: 'Brown', hex: '#7B4A2B' },
	{ name: 'Dark Brown', hex: '#4B3621' },
	{ name: 'Light Brown', hex: '#B5651D' },
	{ name: 'Chocolate', hex: '#5C3A21' },
	{ name: 'Coffee', hex: '#6F4E37' },
	{ name: 'Tan', hex: '#D2B48C' },
	{ name: 'Beige', hex: '#E8DCC0' },
	{ name: 'Khaki', hex: '#C3B091' },
	{ name: 'Bronze', hex: '#CD7F32' },
	{ name: 'Copper', hex: '#B87333' },
	{ name: 'Terracotta', hex: '#E2725B' },
	{ name: 'Caramel', hex: '#AF6E4D' },
	{ name: 'Walnut', hex: '#5B3A29' },
	{ name: 'Wood', hex: '#9B7653' },

	{ name: 'Red', hex: '#C12E1F' },
	{ name: 'Bright Red', hex: '#EE0000' },
	{ name: 'Dark Red', hex: '#8B0000' },
	{ name: 'Crimson', hex: '#DC143C' },
	{ name: 'Maroon', hex: '#800000' },
	{ name: 'Scarlet', hex: '#FF2400' },
	{ name: 'Brick Red', hex: '#9C2A00' },
	{ name: 'Wine', hex: '#722F37' },
	{ name: 'Rose', hex: '#FF007F' },
	{ name: 'Salmon', hex: '#FA8072' },
	{ name: 'Coral', hex: '#FF7F50' },

	{ name: 'Orange', hex: '#FF6A13' },
	{ name: 'Spark Orange', hex: '#FF5B14' },
	{ name: 'Dark Orange', hex: '#FF8C00' },
	{ name: 'Pumpkin', hex: '#FF7518' },
	{ name: 'Amber', hex: '#FFBF00' },
	{ name: 'Peach', hex: '#FFCBA4' },
	{ name: 'Apricot', hex: '#FBCEB1' },

	{ name: 'Yellow', hex: '#F5C211' },
	{ name: 'Sunflower Yellow', hex: '#F5C211' },
	{ name: 'Bright Yellow', hex: '#FFE600' },
	{ name: 'Gold', hex: '#D4AF37' },
	{ name: 'Mustard', hex: '#E1AD01' },
	{ name: 'Lemon', hex: '#FFF44F' },
	{ name: 'Cream', hex: '#FFFDD0' },

	{ name: 'Green', hex: '#00AE42' },
	{ name: 'Bambu Green', hex: '#00AE42' },
	{ name: 'Dark Green', hex: '#006400' },
	{ name: 'Forest Green', hex: '#228B22' },
	{ name: 'Olive', hex: '#808000' },
	{ name: 'Olive Drab', hex: '#6B8E23' },
	{ name: 'Lime', hex: '#BFFF00' },
	{ name: 'Lime Green', hex: '#32CD32' },
	{ name: 'Mint', hex: '#98FF98' },
	{ name: 'Sage', hex: '#9CAF88' },
	{ name: 'Emerald', hex: '#50C878' },
	{ name: 'Teal', hex: '#008080' },
	{ name: 'Turquoise', hex: '#40E0D0' },
	{ name: 'Seafoam', hex: '#93E9BE' },
	{ name: 'Army Green', hex: '#4B5320' },
	{ name: 'Neon Green', hex: '#39FF14' },

	{ name: 'Blue', hex: '#0A2CA5' },
	{ name: 'Navy Blue', hex: '#000080' },
	{ name: 'Dark Navy Blue', hex: '#0B1B3A' },
	{ name: 'Royal Blue', hex: '#4169E1' },
	{ name: 'Sky Blue', hex: '#87CEEB' },
	{ name: 'Baby Blue', hex: '#89CFF0' },
	{ name: 'Powder Blue', hex: '#B0E0E6' },
	{ name: 'Cyan', hex: '#0086D6' },
	{ name: 'Cobalt', hex: '#0047AB' },
	{ name: 'Steel Blue', hex: '#4682B4' },
	{ name: 'Slate Blue', hex: '#6A5ACD' },
	{ name: 'Denim', hex: '#1560BD' },
	{ name: 'Teal Blue', hex: '#367588' },
	{ name: 'Ice Blue', hex: '#D6F1FF' },
	{ name: 'Electric Blue', hex: '#7DF9FF' },

	{ name: 'Purple', hex: '#5E43B7' },
	{ name: 'Violet', hex: '#7F00FF' },
	{ name: 'Indigo', hex: '#4B0082' },
	{ name: 'Lavender', hex: '#B57EDC' },
	{ name: 'Lilac', hex: '#C8A2C8' },
	{ name: 'Plum', hex: '#8E4585' },
	{ name: 'Magenta', hex: '#EC008C' },
	{ name: 'Orchid', hex: '#DA70D6' },
	{ name: 'Mauve', hex: '#E0B0FF' },
	{ name: 'Grape', hex: '#6F2DA8' },

	{ name: 'Pink', hex: '#F55A74' },
	{ name: 'Hot Pink', hex: '#FF69B4' },
	{ name: 'Light Pink', hex: '#FFB6C1' },
	{ name: 'Bubblegum', hex: '#FFC1CC' },
	{ name: 'Fuchsia', hex: '#FF00FF' },
	{ name: 'Blush', hex: '#DE5D83' },

	// Metallics / specialty
	{ name: 'Rose Gold', hex: '#B76E79' },
	{ name: 'Champagne', hex: '#F7E7CE' },
	{ name: 'Pearl', hex: '#EAE0C8' },
	{ name: 'Glow Green', hex: '#CCFFCC' },

	// Full CSS/X11 named colors (so search finds basically anything)
	{ name: 'AliceBlue', hex: '#F0F8FF' }, { name: 'AntiqueWhite', hex: '#FAEBD7' }, { name: 'Aqua', hex: '#00FFFF' },
	{ name: 'Aquamarine', hex: '#7FFFD4' }, { name: 'Azure', hex: '#F0FFFF' }, { name: 'Bisque', hex: '#FFE4C4' },
	{ name: 'BlanchedAlmond', hex: '#FFEBCD' }, { name: 'BlueViolet', hex: '#8A2BE2' }, { name: 'BurlyWood', hex: '#DEB887' },
	{ name: 'CadetBlue', hex: '#5F9EA0' }, { name: 'Chartreuse', hex: '#7FFF00' }, { name: 'Cornflower Blue', hex: '#6495ED' },
	{ name: 'Cornsilk', hex: '#FFF8DC' }, { name: 'DarkCyan', hex: '#008B8B' }, { name: 'DarkGoldenrod', hex: '#B8860B' },
	{ name: 'DarkKhaki', hex: '#BDB76B' }, { name: 'DarkMagenta', hex: '#8B008B' }, { name: 'DarkOliveGreen', hex: '#556B2F' },
	{ name: 'DarkOrchid', hex: '#9932CC' }, { name: 'DarkSalmon', hex: '#E9967A' }, { name: 'DarkSeaGreen', hex: '#8FBC8F' },
	{ name: 'DarkSlateBlue', hex: '#483D8B' }, { name: 'DarkSlateGray', hex: '#2F4F4F' }, { name: 'DarkTurquoise', hex: '#00CED1' },
	{ name: 'DarkViolet', hex: '#9400D3' }, { name: 'DeepPink', hex: '#FF1493' }, { name: 'DeepSkyBlue', hex: '#00BFFF' },
	{ name: 'DodgerBlue', hex: '#1E90FF' }, { name: 'Firebrick', hex: '#B22222' }, { name: 'GoldenRod', hex: '#DAA520' },
	{ name: 'GreenYellow', hex: '#ADFF2F' }, { name: 'Honeydew', hex: '#F0FFF0' }, { name: 'IndianRed', hex: '#CD5C5C' },
	{ name: 'Ivory', hex: '#FFFFF0' }, { name: 'Lavender Blush', hex: '#FFF0F5' }, { name: 'LawnGreen', hex: '#7CFC00' },
	{ name: 'LightCoral', hex: '#F08080' }, { name: 'LightGoldenrod', hex: '#FAFAD2' }, { name: 'LightSalmon', hex: '#FFA07A' },
	{ name: 'LightSeaGreen', hex: '#20B2AA' }, { name: 'LightSkyBlue', hex: '#87CEFA' }, { name: 'LightSteelBlue', hex: '#B0C4DE' },
	{ name: 'MediumAquamarine', hex: '#66CDAA' }, { name: 'MediumBlue', hex: '#0000CD' }, { name: 'MediumOrchid', hex: '#BA55D3' },
	{ name: 'MediumPurple', hex: '#9370DB' }, { name: 'MediumSeaGreen', hex: '#3CB371' }, { name: 'MediumSlateBlue', hex: '#7B68EE' },
	{ name: 'MediumSpringGreen', hex: '#00FA9A' }, { name: 'MediumTurquoise', hex: '#48D1CC' }, { name: 'MediumVioletRed', hex: '#C71585' },
	{ name: 'MidnightBlue', hex: '#191970' }, { name: 'MintCream', hex: '#F5FFFA' }, { name: 'MistyRose', hex: '#FFE4E1' },
	{ name: 'Moccasin', hex: '#FFE4B5' }, { name: 'NavajoWhite', hex: '#FFDEAD' }, { name: 'OldLace', hex: '#FDF5E6' },
	{ name: 'OliveDrab', hex: '#6B8E23' }, { name: 'OrangeRed', hex: '#FF4500' }, { name: 'PaleGoldenrod', hex: '#EEE8AA' },
	{ name: 'PaleGreen', hex: '#98FB98' }, { name: 'PaleTurquoise', hex: '#AFEEEE' }, { name: 'PaleVioletRed', hex: '#DB7093' },
	{ name: 'PapayaWhip', hex: '#FFEFD5' }, { name: 'PeachPuff', hex: '#FFDAB9' }, { name: 'Peru', hex: '#CD853F' },
	{ name: 'Periwinkle', hex: '#CCCCFF' }, { name: 'RosyBrown', hex: '#BC8F8F' }, { name: 'SaddleBrown', hex: '#8B4513' },
	{ name: 'SandyBrown', hex: '#F4A460' }, { name: 'SeaGreen', hex: '#2E8B57' }, { name: 'Seashell', hex: '#FFF5EE' },
	{ name: 'Sienna', hex: '#A0522D' }, { name: 'SlateGray', hex: '#708090' }, { name: 'Snow', hex: '#FFFAFA' },
	{ name: 'SpringGreen', hex: '#00FF7F' }, { name: 'Thistle', hex: '#D8BFD8' }, { name: 'Tomato', hex: '#FF6347' },
	{ name: 'Wheat', hex: '#F5DEB3' }, { name: 'YellowGreen', hex: '#9ACD32' }
];
